parameters:
    pim_enrich.view_element.category.tab.property.template: 'EnhancedEntityBundle:CategoryTree:Tab/property.html.twig'

services:
    pim_enrich.form.type.category:
        class: '%pim_enrich.form.type.category.class%'
        arguments:
            - '%pim_catalog.entity.category.class%'
            - '%pim_catalog.entity.category_translation.class%'
        tags:
            - { name: form.type, alias: pim_category }
        calls:
            - [addEventSubscriber, ['@pim_enhanced_entity.form.subscriber.add_extra_form']]
