language: php

php:
    - "5.5"
    - "5.6"
    - "7.0"

git:
  depth: 10

cache:
  directories:
    - $HOME/.composer/cache

before_install:
    - echo "memory_limit=3G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - phpenv config-rm xdebug.ini
    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - composer self-update --no-interaction

install:
    - composer install --prefer-dist --no-interaction --no-scripts

script:
    - ./bin/php-cs-fixer --dry-run -v fix .
